### ISSUE TITLE
add Security Group IDs to the DAX module

### ISSUE THREAD

**Issue by Pancham97** [peak-ai/terraform-modules#16]
**Is your feature request related to a problem? Please describe.**

When I tried to create a new cluster using the DAX module, I could not create and attach a Security Group with the cluster.

**Describe the solution you'd like**

I would like to have the capability for the DAX module to accept a list of Security Group IDs that could be attached to the cluster.

**Describe alternatives you've considered**

I observed that I could not modify the Security Group post-creation of the cluster. So, this felt like an appropriate solution to the problem.

**Additional context**

**Comment by Pancham97** [comment]
Created a PR for this: https://github.com/peak-ai/terraform-modules/pull/17

**Comment by azhar22k** [comment]
This has been fixed in https://github.com/peak-ai/terraform-modules/releases/tag/v0.9.0
